### ISSUE TITLE
Quota related issues

### ISSUE THREAD

**Issue by SarinaAtkinson-NOAA** [AdyanRios-NOAA/SEFSC-MH-Processing#10]
- When only start year or end year is provided, diff days is not calculating correctly. We may want to process dates differently for quotas because we are using the date fields differently for these management types
- Example cluster 1611 (GOM Reef Fish ACL for red snapper)
- May also need to factor to fishing year

**Comment by AdyanRios-NOAA** [comment]
These quota related issues have been addressed. New quota related issues (multi-reg) will be addressed later.
