### ISSUE TITLE
Species expansion final process flow

### ISSUE THREAD

**Issue by SarinaAtkinson-NOAA** [AdyanRios-NOAA/SEFSC-MH-Processing#47]
- [x] mh_pre_process.R is going to be for only sector expansion and creating other variables needed for processing
- [x] mh_process.R creates clusters and fills in dates
- [x] spcies_expansion.R gets dataset ready for collections at the species level and dates are cleaned up
- [x] Review date cleanup

**Comment by AdyanRios-NOAA** [comment]
Expansion happens after date sorting
