### ISSUE TITLE
Review code for filling in dates

### ISSUE THREAD

**Issue by SarinaAtkinson-NOAA** [AdyanRios-NOAA/SEFSC-MH-Processing#67]
Change date logic may not be working as intended 

- Example cluster 14 where diff days = -1 and two records have the same ineffective date
     - Two records with same effective date because of a change in species aggregates
     - Should that record where bag limit flagged for change in a species aggregate be captured? By including this record it is giving us an ineffective date that produces a gap in our timeline.
- What is happening with other clusters where diff_days = -1? Is it a similar issue with species agg/groups changing?

**Comment by AdyanRios-NOAA** [comment]
No need to investigate the csv file for the consecutive adjustments in Cluster 847. I think I was able to figure out the recursions after our 7/19 meeting! Looking forward to reviewing the code next Tuesday.

**Comment by AdyanRios-NOAA** [comment]
Diff days and multi-reg to be addressed later, date processing is working for everything else
To investigate that we would start again as changes have been made to clusters and sorting since this issue was documented
