### ISSUE TITLE
Revisit special dates case from Start date < Effective date issue

### ISSUE THREAD

**Issue by katgodwin** [AdyanRios-NOAA/SEFSC-MH-Processing#72]
From #69, final decision was to create rule that over rides start date when start date is prior to effective date. In these occurrences, start date will be advanced to effective date. 

The remaining records which this rule does not work well for are Reg_ID 4549, 4552, and 4548. These are quota records for the 2016-2017 seasonal fishing seasons that are modified in May 2017. The necessary 2016 start year does not work with the new rule. Come back to this issue after further analysis of the database.

**Comment by AdyanRios-NOAA** [comment]
Incorporated necessary changes to date processing logic
