### ISSUE TITLE
Data Processing Metadata

### ISSUE THREAD

**Issue by GaitlynMalone** [AdyanRios-NOAA/SEFSC-MH-Processing#75]
- [x] Update Data Processing Metadata document
- [ ] Review updates
- [ ] Publish Version 1

**Comment by SarinaAtkinson-NOAA** [comment]
draft created in[ folder](https://drive.google.com/drive/folders/1AMWfX7gZmALo5APQ9cUPCmFCEUbfrOMg). After some steps move to ODM, the processing metadata will need to be updated.
