### ISSUE TITLE
Spanish Mackerel Cross Check

### ISSUE THREAD

**Issue by GaitlynMalone** [AdyanRios-NOAA/SEFSC-MH-Processing#76]
- [x] Gather corresponding records
- [x] Cross-check with provided Management History
- [x] Create working paper
- [x] Review working paper with MH leadership, receive edits, and subsequent approval
- [x] Request working paper number
- [x] Submit working paper
- [x] Circulate latest WP draft internally @katgodwin 
- [x]  Prep cross check overview email @GaitlynMalone
- [x] Talk to Lisa first about multiple FMPS @AdyanRios-NOAA
- [x] Find out who provided the history for SEDAR @AdyanRios-NOAA

**Comment by katgodwin** [comment]
tables for closures are proving harder to simplify than anticipated due to wide range of regions and subsectors included in records.

**Comment by katgodwin** [comment]
Reworking sorting of closures and gear restrictions: 
subsector - zone - region - effective date
break up tables by management type: closure, prohibited gear, gear restrictions

**Comment by katgodwin** [comment]
Discrepancies between given data and database pull for gear restrictions and spatial closures: provided data included spatial closures and gear restrictions for Gulf Reef Fish fishery "All Species" regulations. 
Do those "all species" regulations that are within the same region (GOM) impact other FMP species (Spanish mackerel)?

**Comment by AdyanRios-NOAA** [comment]
To what extent do we need to think about other FMPs?

**Comment by AdyanRios-NOAA** [comment]
Should we collapse across spatial closures and gear restrictions. Gears can be area specific. Areas can be gear specific.

**Comment by AdyanRios-NOAA** [comment]
Do we have a caution for regulations that point to proposed rules?

**Comment by AdyanRios-NOAA** [comment]
Ideally, once we transition to SERO, hopefully they also make the FRs as self descriptive as possible.

**Comment by SarinaAtkinson-NOAA** [comment]
Working paper submitted to SEDAR
