### ISSUE TITLE
Address Data Bugs in ODM

### ISSUE THREAD

**Issue by GaitlynMalone** [AdyanRios-NOAA/SEFSC-MH-Processing#80]
- [x] Check in with Yanet that bugs can be assigned to a particular user (6/23/2022) and that we can start entering them
- [x] Send email to Yanet with all orphan records to be expired
- [x] Enter records again for expired orphan records with no bugs attached (15)
- [x] Finish addressing current bugs (orphan records with data bugs that have to re-entered correctly making bugs irrelevant) (1 out of 174 remaining due to comments from testers)- expire/close bugs first or after?
- [x] Enter new data bugs in the system that are coded in R
- [x] Compare result to R output
- [x] Update R script
- [x] Enter new data bugs (0 out of 51 remaining) not in R code

**Comment by GaitlynMalone** [comment]
Currently waiting on two features to be added:
- The ability to add a record and register a change in the system log
- The ability to address subsequent data bugs for records with previous data bugs that have been closed and moved to master

**Comment by vmatter-NOAA** [comment]
@GaitlynMalone @katgodwin 
emailed Yanet on 7/14/22
please test functionality for _The ability to address subsequent data bugs for records with previous data bugs that have been closed and moved to master_

**Comment by katgodwin** [comment]
7/14/22 - I tried to edit data bugs related to 75 FR 27217, Data bug IDs 6026, 6027, and 6028. Bud ID 6036 worked but when I went to close and move to master the others did not show the save/move to master buttons after data bug closure. Not sure what happened.

**Comment by GaitlynMalone** [comment]
The new process worked for 52 FR 2113 Reg ID 165. Changes were made, saved, and validated and the Bug was closed. Change is reflected in master.

**Comment by GaitlynMalone** [comment]
Error moving 63 FR 18144 to master. Data bugs 7136 and 7137 have been addressed, validated, and closed but I receive an error when attempting to move the file to master.

**Comment by GaitlynMalone** [comment]
Remaining items:
- Validations for Prohibited Gear record (59 FR 966)
- Deleting Entire Files (85 FR 50334 and 85 FR 50333)
- Add Minimum Size Limit Adjustment Management Type

Orphan Bugs:
- 47 FR 13353 (Reg ID 3254)
- 47 FR 21256 (Reg ID 3383)
- 72 FR 54223 (Reg IDs 5474, 5473, 5472, 5471, 5427)
- 78 FR 17882 (Reg ID 2440)
- 78 FR 18247 (Reg IDs 2272, 2197)

**Comment by vmatter-NOAA** [comment]
Error when adding new management type
![image](https://user-images.githubusercontent.com/71509626/183120634-64b4abe9-c29d-4e8b-9c50-f7d880953086.png)

**Comment by vmatter-NOAA** [comment]
> Error when adding new management type ![image](https://user-images.githubusercontent.com/71509626/183120634-64b4abe9-c29d-4e8b-9c50-f7d880953086.png)

In the future you should use this IP address to make changes to the LOV:
https://199.242.232.172:8443/apex/f?p=113

**Comment by GaitlynMalone** [comment]
One remaining bug open in the database
    - Bug relates to CMP and the addition of records for Amendment 6 
    - Looking into whether or not these records need to be added @GaitlynMalone

**Comment by AdyanRios-NOAA** [comment]
After comparison of all records that have always had a reg_ID we found the following:
- [ ] Discovered two additional bug that need to be added to the latest ODM extraction
  - [ ] One related to flag (REG_ID 1477)
  - [ ] Species selected (223)
- [ ] Discovered that aggregates is causing all to show up for species
- [ ] Management Status == Once (revisit this validation)

This covers the investigation across 5350 of 5393 records (99.2%)
Remaining 16 data bugs (14 new, and 2 described above) ready to be made after completing the cross check.
