### ISSUE TITLE
Updates for and from the team

### ISSUE THREAD

**Issue by AdyanRios-NOAA** [AdyanRios-NOAA/SEFSC-MH-Processing#82]
Data bugs
- https://docs.google.com/spreadsheets/d/14kR7OPkiOkdazuWUb7_DvDmbhZJihbCe/edit#gid=462168367
- 428 with 253 remaining
- Goal next week, compare corrected bug/master system with manual process in R (BE CAUGHT UP ON BUGS)
- *Need to figure out blank management status* (meet briefly or email Yanet re this lov, other lovs allow selecting blanks)
- Hold off on new bugs, first try to match the R process
- *Need to figure and be sure that adding a record registers as a change in the system log* (Check with Yanet)

Comparisons for SEDAR
- Red snapper is done
- Gray Trigger ready to go out
- Caribbean Closures ready to go out
- Spanish (CMP)
  - rec quotas, might be missing from MH (GM)
  - gear restrictions (theirs was very generalized, ours are compartmentalized) KM
  - https://docs.google.com/document/d/1KEChL6BipovyH6d2ojkAUJ7xVCfuIMgi/edit
- Management types are grouped into different tables (summary list will guide increased automation reproducibility of the semi manually created tables thus far) - (also pay attention to how clusters are sorted within the tables, to reproduce that in R)

Code automation
- Working towards "saturated" tables (correct start and end dates associated with overwriting or temporary changes)
   - This will allow further building out of datasets for plots and analysis formats
   - This will allow automation of the SEDAR comparison tables build semi-manually so far
- Subsector forks *Can be another high priority after bugs*
   - Already looked at: RF-GOM, SA-SG, CMP, CAR-RF, SL-GOM, Shrimp-GOM, DolphinWahoo
  
SERO demo (DATA INPUT)   PPT
- Further along (we are still coding data output)
- Data are up to date through 2021
- Have demos, but have not practiced
- Metadata and Demos have not substantially changed (with recent yante updates), but user manual linked in ODM MH manual probably needs to be updated (alter/ask yanet about)

SERO and Council demos (DATA OUTPUT/Processing)
- We suggest two offerings (deep dive, and medium dive) 
  - We have a red snapper example for the deep dive (covers a little of how processing works)
  - Final clean variables and structure would be medium dive
  - Working on a visual (map) of the analysis ready data
     - For example: Clusters, Adjustments, Species Aggregates and Groups, Zones, Sector Forks, Collections
  - Our current repository gets us to analysis ready "A" (operates at the cluster level) - gets to the format shown in the "Comparisons for SEDAR documents"
  - A second repository is in mind to offer versioned releases of the cluster level analysis ready dataset AND get at the next mutations of that dataset to become figures and merge with data as needed

**Comment by vmatter-NOAA** [comment]
_Need to figure out blank management status (meet briefly or email Yanet re this lov, other lovs allow selecting blanks)
Need to figure and be sure that adding a record registers as a change in the system log (Check with Yanet)_

email sent to Yanet 6/28/22

**Comment by vmatter-NOAA** [comment]
_SERO demo (DATA INPUT) PPT_

- [ ] @AdyanRios-NOAA will find latest copy of data manager user manual
- [ ] @GaitlynMalone @katgodwin please estimate time to update this document
- [ ] schedule dry run of presentation with MH team
- [ ] @vmatter-NOAA will schedule SERO demo

**Comment by AdyanRios-NOAA** [comment]
Currently locked out of my data manager ODM account. New passwords requested. I will find and share data manager user guide later today.

**Comment by AdyanRios-NOAA** [comment]
Shared [here](https://docs.google.com/document/d/1UeH7K2WGATBcK3A_8mKwO6p8bt73GVHjDdX8wBg3fRc/edit?usp=sharing)

A question to bring up later: Does the documented process change now that will be no double blind?

**Comment by vmatter-NOAA** [comment]
> Shared [here](https://docs.google.com/document/d/1UeH7K2WGATBcK3A_8mKwO6p8bt73GVHjDdX8wBg3fRc/edit?usp=sharing)
> 
> A question to bring up later: Does the documented process change now that will be no double blind?

@AdyanRios-NOAA this document appears to be a Data User- User Guide, not a Data Manager User Guide. There is no mention in inputting data, only searching master and entering bugs. We will still need to update this document before we present to Councils though. @katgodwin has looked and doesn't think it will take to long to update this. However, to update the screenshots they will need a Data User login. They will request that from Yanet. One will have an extra login as a User and the other will have an extra login as a Data manager to update the user guide we will use for SERO (data manager).

Yes the screen shots will need to be updated in the data manager guide to reflect 1) interactive grid and 2) single data entry.

**Comment by vmatter-NOAA** [comment]
_SERO and Council demos (DATA OUTPUT/Processing)_

**Comment by AdyanRios-NOAA** [comment]
screen shot task moved to #83

**Comment by AdyanRios-NOAA** [comment]
- [ ] remaining data bugs relate to adding records and subsequent data bugs (~49 + ~76) see #83
- [ ] check back with SEDAR for Caribbean reference document number @AdyanRios-NOAA 
- [ ] we need to find more time processing @AdyanRios-NOAA 
- [ ] scheduling with SERO @vmatter-NOAA 
- [ ] we still need a disclaimer (ask SERO, check opensource like R)

**Comment by AdyanRios-NOAA** [comment]
Remaining open tasks were re-located to issue 88
