### ISSUE TITLE
Update ODM User Manuals

### ISSUE THREAD

**Issue by AdyanRios-NOAA** [AdyanRios-NOAA/SEFSC-MH-Processing#83]
User Manual (data user) - @katgodwin 
User Manual (data manager) - @GaitlynMalone (Priority for SERO)
- In data manager profile buttons have location issues
  - no tab upload
  - data entry log comes up blank
  - validation log
  - species look up (algal species)
  
- [x]  Schedule meeting with Yanet
- [x] User Manual Outline (data user) @katgodwin 
- [x] User Manual Outline (data manager) @GaitlynMalone

**Comment by GaitlynMalone** [comment]
ODM-MH User Roles Meeting (7/20/2022)
Features to be added/removed in Data Manager profile:
- [ ] Remove Management History Dataset dropdown menu
- [ ] Add the ability to view species information for each FMP on the FMP Master Detail page (accessed using magnifying glass icon next to an FMP on the FMP Maintenance page)
- [ ] Add the ability to access the metadata document from the dashboard on the Home page

To Do:
- [ ] Provide Yanet with updated Data User guide for database
- [ ] Provide Yanet with updated Data Manager guide for database

**Comment by katgodwin** [comment]
Data User Guide tasks:

- [ ] update screen shots
- [ ] spell check and update language
- [ ] update links 
- [ ] update aesthetic of document to match other documents
- [ ] gain access to old user document and compare content
- [ ] do final look through

**Comment by GaitlynMalone** [comment]
- [Data Manager User Guide](https://docs.google.com/document/d/1TH7QA_HDSrajvZEOd-W1P2MjTgO54lby/edit?mode=html#heading=h.gjdgxs)

- [Date User User Guide ](https://docs.google.com/document/d/1R7S7RC2rT76zFYBO9GWjKLZyJdM4EHpq3Ez513P7Jek/edit?mode=html)
