### ISSUE TITLE
_SERO demo (DATA INPUT) PPT_

### ISSUE THREAD

**Issue by vmatter-NOAA** [AdyanRios-NOAA/SEFSC-MH-Processing#84]
_SERO demo (DATA INPUT) PPT_

- [x] update [SERO document](https://docs.google.com/document/d/1PJShXWNjZo2tj0DxHCoIJ5nVkkyZjoMIwbi-vC5dTxI/edit?usp=sharing); download DM guide from ODM; combine the two in one @GaitlynMalone 
- [x] schedule dry run of presentation with MH team
- [x] @vmatter-NOAA will schedule SERO demo
     - [x] @vmatter-NOAA email Jessica Stephens for updated list of participants

_Originally posted by @vmatter-NOAA in https://github.com/AdyanRios-NOAA/SEFSC-MH-Processing/issues/82#issuecomment-1169390814_

**Comment by AdyanRios-NOAA** [comment]
Review user manuals (they need to be uploaded to ODM)
- 
- [ ] @vmatter-NOAA 
- [ ] @AdyanRios-NOAA 

- [ ] Draft introductory email based on information shared previously @vmatter-NOAA @vmatter-NOAA

**Comment by GaitlynMalone** [comment]
@GaitlynMalone & @katgodwin To Do List:
- [ ] Update dataset/database language
- [ ] Separate videos on slide 10 to each slide
- [ ] Create video for FMP Website search
- [ ] Demo reviewing eCFR
- [ ] Demo reviewing Proposed Rule
- [ ] Demo of tabular entry
- [ ] Remove status of captured regulations slide and add text to tabular entry slide
- [ ] Discuss recording demonstration to add to the end of the slideshow
- [ ] Slide with what data entry tips document covers (nuanced cases)
- [ ] Data managers users guide slide

**Comment by katgodwin** [comment]
videos uploaded have a solid black screen cap, don't know how to fix

**Comment by katgodwin** [comment]
does the field dashboard need the data manager view?

**Comment by katgodwin** [comment]
Put a pin in it: 
Fix permissions on metadata
