### ISSUE TITLE
Working paper Flextable demos

### ISSUE THREAD

**Issue by katgodwin** [AdyanRios-NOAA/SEFSC-MH-Processing#93]
**mh_tables.R**
To attempt to automate the working paper tables, we used flextables in R to demo this process. 
To begin I looked at the process of creating tables for the CAR closures paper and the Gray triggerfish paper: 
_Caribbean closures process –_ 
Load dataset
Select Caribbean region
Select management types closure/reopening, prohibited species, and fishing season to determine clusters selected. 
Sort by sector, subsector, closure type
Then sort by species or zone depending on complexity
Arrange by start date

_Gray Triggerfish - size limits, annual catch limits (ACLs), trip limits, bag limits, and closures_
Load dataset
Select south Atlantic gray triggerfish
Select management type (either min/max size limit, ACL, trip limits, bag limits, or closure/reopenings)
Sort by sector then region-zone
Arrange by start date

From here clusters were identified to start the flextable demos. 

**mh_flextable_demo.R**
Here Sarina and the team started a simple flextable demo for cluster 1203 representing commercial minimum size limits for Gray triggerfish. 
Important things to consider are arrangement by zone and date to show proper timeline. 

**mh_flex_spmackerel.R**
_Cluster 1032_
I changed how the table is arranged to fix the date order to ensure a correct timeline. I changed it from zone, start_date to zone, start_year, start_date. 
Dates are lining up correctly, but CMP zones are weird, may have to look into those (migratory zones vs generic zones)

**mh_flex_grtriggerfish.R**
1. Com Size Limits - Cluster 1203 - see mh_flextable_demo.R
2. Rec Size Limits - Cluster 1200
3. Com ACL - Cluster 1142

_Cluster 1200 - rec size limits_ 
Works well, everything looks good. 

_Cluster 1142 - com ACL_
Need to add start day/month columns for ACL because values change from applying all year to applying from Jan-June and July-Dec.

**Comment by AdyanRios-NOAA** [comment]
demo tables will be referred to for key examples of producing clean output from MH
