### ISSUE TITLE
Region/Zone formatting 

### ISSUE THREAD

**Issue by katgodwin** [AdyanRios-NOAA/SEFSC-MH-Processing#97]
**_No Formatting Changes Needed:_** 

- Atlantic  Coast Red Drum Fishery
- Dolphin sand Wahoo Fishery Off the Atlantic States
- Golden Crab Fishery of the South Atlantic 
- Queen Conch Resources of Puerto Rico and the U.S. Virgin Islands
- Red Drum Fishery of the Gulf of Mexico 
- Reef Fish Fishery of Puerto Rico and the U.S. Virgin Islands
- Reef Fish Resources of the Gulf of Mexico*
    *There were changes that have already been addressed
- Shrimp Fishery of the Gulf of Mexico
- Shrimp Fishery of the South Atlantic
- Spiny Lobster Fishery of the Gulf of Mexico and South Atlantic 

**_Formatting Changes Needed:_** 

- Coastal Migratory Pelagic Resources - SATL: Atlantic Migratory Group Spanish Mackerel - South of 30°42'45.6¿ N. Lat.
   - change to: SATL: Atlantic Migratory Group Spanish Mackerel - South of 30°42'45.6" N. Lat.
- Coastal Migratory Pelagic Resources - SATL: Atlantic Migratory Group Spanish Mackerel - Between 29°25' N. Lat and 25°20.24¿ N. Lat.
   - change to: SATL: Atlantic Migratory Group Spanish Mackerel - Between 29°25' N. Lat and 25°20.24" N. Lat.
- Snapper-Grouper Fishery of the South Atlantic Region - SATL: North of Cape Canaveral - Off of North Carolina and South Carolina
   - remove and replace with existing region:zone of SATL: Off of North Carolina and South Carolina*
     *I believe the three records using this zone (REG ID 2050, 2053, and 2252) were entered incorrectly as "Off of North Carolina and South Carolina" is a smaller zone than "North of Cape Canaveral" so the "North of Cape Canaveral" is not a necessary specification
- Snapper-Grouper Fishery of the South Atlantic Region - SATL: Off the Southern Atlantic States
   - remove and replace with existing region:zone of SATL: ALL*
     *I believe the record recorded using this zone did so because it is the exact wording of the FR; however, based on my search of the dataset it appears it is the same zone as SATL: ALL (REG ID 1428)
- Snapper-Grouper Fishery of the South Atlantic Region - SATL:  South of 35°15.9' N. Lat
- Snapper-Grouper Fishery of the South Atlantic Region - SATL:  South of 35°15.9' N. Lat, Cape Hatteras Light, North Carolina
- Snapper-Grouper Fishery of the South Atlantic Region - SATL: South of Cape Hatteras, NC
   - I believe the above three zones can be consolidated under one name as they all are referencing the same location (REG IDs 1565, 1578, 11507, 11508, 145, 214, 211, 210, and 1605)
- Spiny Lobster Fishery pf Puerto Rico and the U.S. Virgin Islands - CAR: St Croix
   - remove and replace with existing region:zone of CAR: St. Croix Management Area*
     *The summary section of the FR using this zone states that the fishing season adjustment is applicable to the St. Croix Management Area (REG ID 37355)

To complete this check I used the Sept 20, 2022 download of the MH Dataset found below. 
[Zone formatting.xlsx](https://github.com/AdyanRios-NOAA/SEFSC-MH-Processing/files/9669183/Zone.formatting.xlsx)

**Comment by AdyanRios-NOAA** [comment]
Thank you @katgodwin!!

**Comment by AdyanRios-NOAA** [comment]
Notes moved over to new repo
